version: "3.8"

services:
  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./logs:/var/log/nginx
      - ~/Desktop/ACD/acd-front:/var/www/acd-management/acd-front/
      - ~/Desktop/ACD/acd-front-final:/var/www/acd-management-v2/acd-front-final
    networks:
      - global-network
    expose:
      - "80"

networks:
  global-network:
    external: true
