version: "3.8"

services:
  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./logs:/var/log/nginx
      - /var/www/acd-management/acd-front/:/var/www/acd-management/acd-front/
      - /var/www/acd-management-v2/acd-front-final:/var/www/acd-management-v2/acd-front-final
      - /etc/nginx/ssl/:/etc/nginx/ssl/
    networks:
      - global-network
    expose:
      - "80"
      - "443"
networks:
  global-network:
    external: true
